version: "3.8"
services:
  front:
    build: ./carros_facisa_front
    ports:
      - "3000:80"
  
  back:
    build: ./carros-facisa-back
    environment:
      - DATABASE_URL=mongodb://mongo:27017/carrosdb
    ports:
      - "5000:5000"
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"

volumes:
  mongo-data:
