apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mongo-service
    app: carros-facisa-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: carros-facisa-app
