apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app: carros-facisa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-pod
      app: carros-facisa-app
  template:
    metadata:
      name: mongo-pod
      labels:
        name: mongo-pod
        app: carros-facisa-app
    spec:
      containers:
        - name: mongo
          image: mongo
          ports: 
            - containerPort: 27017
          env:
            - name: AUTH
              value: "no"
